services:
  backend:
    build:
      context: ./backend
    container_name: laravel_app
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      #- ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: react_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: migrate_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
